# Generated by Django 3.2.8 on 2021-10-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreC', models.CharField(max_length=255)),
                ('apellidoC', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=255)),
                ('telefonoC', models.CharField(max_length=255)),
                ('teleCasaC', models.CharField(max_length=255)),
                ('suscripcion', models.CharField(max_length=255)),
                ('descripcionC', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
