# Generated by Django 3.2.8 on 2021-10-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_auto_20211028_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreD', models.CharField(max_length=255)),
                ('Monto', models.CharField(max_length=255)),
                ('fecha', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreP', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('precioU', models.CharField(max_length=255)),
                ('productoA', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoD', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreT', models.CharField(max_length=255)),
                ('repetir', models.CharField(max_length=255)),
                ('relacionado', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('prioridad', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='empresa',
        ),
    ]
